### ISSUE TITLE
Git error when adding non-existing directory

### ISSUE THREAD

**Issue by distorhead** [flant/werf#1043]
Given config:

```
git:
- add: /.helm/script/
  to: /app/.helm/script/
```

If there is no `.helm/script` in the repo, then dapp fails:

```
/home/gitlab-runner/.rvm/gems/ruby-2.4.1@dapp-0.35/gems/dapp-0.35.31/lib/dapp/dimg/git_artifact.rb:247:in `is_empty': error creating archive for commit `d557d9f8c1068af54da84a6f2361bf5379ad01a5`: base path `/.helm/script` entry not found repo (RuntimeError)
	from /home/gitlab-runner/.rvm/gems/ruby-2.4.1@dapp-0.35/gems/dapp-0.35.31/lib/dapp/dimg/dimg/git_artifact.rb:33:in `block in generate_git_artifacts'
	from /home/gitlab-runner/.rvm/gems/ruby-2.4.1@dapp-0.35/gems/dapp-0.35.31/lib/dapp/dimg/dimg/git_artifact.rb:32:in `select'
	from /home/gitlab-runner/.rvm/gems/ruby-2.4.1@dapp-0.35/gems/dapp-0.35.31/lib/dapp/dimg/dimg/git_artifact.rb:32:in `generate_git_artifacts'
	from /home/gitlab-runner/.rvm/gems/ruby-2.4.1@dapp-0.35/gems/dapp-0.35.31/lib/dapp/dimg/dimg/git_artifact.rb:14:in `block (2 levels) in local_git_artifacts'
	from /home/gitlab-runner/.rvm/gems/ruby-2.4.1@dapp-0.35/gems/dapp-0.35.31/lib/dapp/dimg/dimg/git_artifact.rb:13:in `map'
	from /home/gitlab-runner/.rvm/gems/ruby-2.4.1@dapp-0.35/gems/dapp-0.35.31/lib/dapp/dimg/dimg/git_artifact.rb:13:in `block in local_git_artifacts'
	from /home/gitlab-runner/.rvm/gems/ruby-2.4.1@dapp-0.35/gems/dapp-0.35.31/lib/dapp/dimg/dimg/git_artifact.rb:10:in `tap'
	from /home/gitlab-runner/.rvm/gems/ruby-2.4.1@dapp-0.35/gems/dapp-0.35.31/lib/dapp/dimg/dimg/git_artifact.rb:10:in `local_git_artifacts'
	from /home/gitlab-runner/.rvm/gems/ruby-2.4.1@dapp-0.35/gems/dapp-0.35.31/lib/dapp/dimg/dimg/git_artifact.rb:6:in `git_artifacts'
	from /home/gitlab-runner/.rvm/gems/ruby-2.4.1@dapp-0.35/gems/dapp-0.35.31/lib/dapp/dimg/build/stage/ga_latest_patch.rb:21:in `empty?'
```

**Comment by alexey-igrychev** [comment]
v1.0.0
```
Error: build failed: error creating archive for commit `cc35898ac9e3333e508b1f3902bdf8812c0d61d5`: base path `/.helm/script` entry not found repo
```
