### ISSUE TITLE
dapp 0.36 kubedog-related panic

### ISSUE THREAD

**Issue by distorhead** [flant/werf#1454]
```
fatal error: concurrent map iteration and map write

goroutine 843 [running]:
runtime.throw(0x19f0f60, 0x26)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc00139daf0 sp=0xc00139dac0 pc=0x42d2d2
runtime.mapiternext(0xc00139dbe0)
	/usr/local/go/src/runtime/map.go:790 +0x525 fp=0xc00139db78 sp=0xc00139daf0 pc=0x410925
github.com/flant/kubedog/pkg/utils.IsReplicaSetNew(0xc002360900, 0xc00097aa20, 0xc00083be20, 0x11, 0xc0005bda01, 0x0, 0x0)
	/home/distorhead/go/src/github.com/flant/kubedog/pkg/utils/deployment_utils.go:171 +0xa8 fp=0xc00139dc50 sp=0xc00139db78 pc=0xfee718
github.com/flant/kubedog/pkg/tracker.(*DeploymentTracker).runPodTracker.func2(0xc000ab77a0, 0xc0005d9dc0, 0xc00083be20, 0x11, 0xc000afd380, 0xc000afd3e0)
	/home/distorhead/go/src/github.com/flant/kubedog/pkg/tracker/deployment.go:510 +0x649 fp=0xc00139dfb0 sp=0xc00139dc50 pc=0x11e1969
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00139dfb8 sp=0xc00139dfb0 pc=0x45a5d1
created by github.com/flant/kubedog/pkg/tracker.(*DeploymentTracker).runPodTracker
	/home/distorhead/go/src/github.com/flant/kubedog/pkg/tracker/deployment.go:506 +0x1ff

goroutine 1 [select]:
github.com/flant/kubedog/pkg/tracker.TrackDeployment(0xc0005ddd98, 0x7, 0xc000452330, 0x10, 0x1bf0d40, 0xc0004d6000, 0x1bd7ce0, 0xc000834500, 0x0, 0x0, ...)
	/home/distorhead/go/src/github.com/flant/kubedog/pkg/tracker/deployment.go:56 +0x67a
github.com/flant/kubedog/pkg/trackers/rollout.TrackDeploymentTillReady(0xc0005ddd98, 0x7, 0xc000452330, 0x10, 0x1bf0d40, 0xc0004d6000, 0x0, 0x0, 0x0, 0xbf2387d520daa1c8, ...)
	/home/distorhead/go/src/github.com/flant/kubedog/pkg/trackers/rollout/deployment.go:66 +0x300
github.com/flant/dapp/pkg/deploy.trackDeployments(0xc000634dc0, 0xbf2387d520daa1c8, 0x121f1c9f1, 0x2c75d60, 0xc000452330, 0x10, 0xc0003c3880, 0x6, 0x8, 0xc00060a6c0, ...)
	/home/distorhead/go/src/github.com/flant/dapp/pkg/deploy/helm.go:199 +0x28b
github.com/flant/dapp/pkg/deploy.doDeployHelmChart(0xc0003e7600, 0x34, 0xc000373500, 0x27, 0xc000452330, 0x10, 0xc0003c3880, 0x6, 0x8, 0xc00060a6c0, ...)
	/home/distorhead/go/src/github.com/flant/dapp/pkg/deploy/helm.go:152 +0xc8d
github.com/flant/dapp/pkg/deploy.DeployHelmChart.func1(0xc0004d4450, 0x1bac340)
	/home/distorhead/go/src/github.com/flant/dapp/pkg/deploy/helm.go:92 +0x85
github.com/flant/dapp/pkg/lock.(*Base).WithLock(0xc0004d4450, 0x1bac340, 0xc0004d4480, 0xc00016f170, 0x17fccc0, 0x1b9344d)
	/home/distorhead/go/src/github.com/flant/dapp/pkg/lock/base.go:70 +0x60
github.com/flant/dapp/pkg/lock.(*File).WithLock(0xc0004d4450, 0x4e94914f0000, 0xc0003a2900, 0xc00060a6e0, 0xc00016f170, 0xc0003a2900, 0x34)
	/home/distorhead/go/src/github.com/flant/dapp/pkg/lock/file.go:57 +0xa5
github.com/flant/dapp/pkg/lock.WithLock(0xc0003a29c0, 0x34, 0x0, 0x0, 0xc00016f170, 0xc0003a29c0, 0x34)
	/home/distorhead/go/src/github.com/flant/dapp/pkg/lock/lock.go:56 +0x107
github.com/flant/dapp/pkg/deploy.withLockedHelmRelease(0xc000373500, 0x27, 0xc00016f170, 0xc000054790, 0xc0000547a0)
	/home/distorhead/go/src/github.com/flant/dapp/pkg/deploy/helm.go:87 +0xd0
github.com/flant/dapp/pkg/deploy.DeployHelmChart(0xc0003e7600, 0x34, 0xc000373500, 0x27, 0xc000452330, 0x10, 0xc0003c3880, 0x6, 0x8, 0xc00060a6c0, ...)
	/home/distorhead/go/src/github.com/flant/dapp/pkg/deploy/helm.go:91 +0xc8
github.com/flant/dapp/pkg/deploy.(*DappChart).Deploy(0xc0005f2820, 0xc000373500, 0x27, 0xc000452330, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/distorhead/go/src/github.com/flant/dapp/pkg/deploy/dapp_chart.go:105 +0x2c5
github.com/flant/dapp/pkg/deploy.RunDeploy(0xc000373500, 0x27, 0xc00048cde0, 0x16, 0xc000045540, 0x3b, 0xc000452330, 0x10, 0xc000373530, 0x2c, ...)
	/home/distorhead/go/src/github.com/flant/dapp/pkg/deploy/deploy.go:95 +0x683
main.runDeploy(0xc00048cde0, 0x16, 0xc000045540, 0x3b, 0xc000373500, 0x27, 0xc00048ce00, 0x15, 0x0, 0x0, ...)
	/home/distorhead/go/src/github.com/flant/dapp/cmd/deploy/deploy.go:23 +0x238
main.main.func1(0xc000328c90, 0x58, 0xc000328c90, 0x0, 0x0)
	/home/distorhead/go/src/github.com/flant/dapp/cmd/deploy/main.go:303 +0x803
github.com/flant/dapp/pkg/ruby2go.RunCli(0x19c3417, 0x6, 0x1a766c8)
	/home/distorhead/go/src/github.com/flant/dapp/pkg/ruby2go/ruby2go.go:103 +0x37d
main.main()
	/home/distorhead/go/src/github.com/flant/dapp/cmd/deploy/main.go:19 +0x42

goroutine 19 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x2c760a0)
	/home/distorhead/go/src/k8s.io/klog/klog.go:943 +0x8b
created by k8s.io/klog.init.0
	/home/distorhead/go/src/k8s.io/klog/klog.go:403 +0x69

goroutine 20 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 9 [chan receive, 2 minutes]:
github.com/flant/dapp/pkg/ruby2go.Trap.func1(0xc0000b9f20)
	/home/distorhead/go/src/github.com/flant/dapp/pkg/ruby2go/ruby2go.go:124 +0x5b
created by github.com/flant/dapp/pkg/ruby2go.Trap
	/home/distorhead/go/src/github.com/flant/dapp/pkg/ruby2go/ruby2go.go:122 +0xf4

goroutine 10 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/local/go/src/runtime/time.go:105 +0x14f
github.com/flant/dapp/pkg/process_exterminator.run(0xc0000454c0, 0x6, 0x8)
	/home/distorhead/go/src/github.com/flant/dapp/pkg/process_exterminator/main.go:50 +0x1ad
created by github.com/flant/dapp/pkg/process_exterminator.Init
	/home/distorhead/go/src/github.com/flant/dapp/pkg/process_exterminator/main.go:26 +0x9f

goroutine 227 [chan send, 1 minutes]:
github.com/flant/kubedog/pkg/tracker.(*EventInformer).Run.func4(0xc000255560, 0xc000325380)
	/home/distorhead/go/src/github.com/flant/kubedog/pkg/tracker/event_informer.go:118 +0x1e5
created by github.com/flant/kubedog/pkg/tracker.(*EventInformer).Run
	/home/distorhead/go/src/github.com/flant/kubedog/pkg/tracker/event_informer.go:75 +0x168

goroutine 23 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x7f6ae7770ff0, 0x72, 0xc000070a88)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000258098, 0x72, 0xffffffffffffff00, 0x1ba8f40, 0x2bf4538)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000258098, 0xc000457000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000258080, 0xc000457000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000258080, 0xc000457000, 0x1000, 0x1000, 0xc000070b70, 0x4571c0, 0xc000000300)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000b6020, 0xc000457000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x68
net/http.(*persistConn).Read(0xc0001b87e0, 0xc000457000, 0x1000, 0x1000, 0xc000070c70, 0x406be5, 0xc000094480)
	/usr/local/go/src/net/http/transport.go:1497 +0x75
bufio.(*Reader).fill(0xc00027c720)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc00027c720, 0x1, 0x0, 0x0, 0x1, 0xc0000944e0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0x3f
net/http.(*persistConn).readLoop(0xc0001b87e0)
	/usr/local/go/src/net/http/transport.go:1645 +0x1a2
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1338 +0x941

goroutine 24 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc0001b87e0)
	/usr/local/go/src/net/http/transport.go:1885 +0x113
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1339 +0x966

goroutine 183 [chan send, 1 minutes]:
github.com/flant/kubedog/pkg/tracker.TrackJob.func1(0xc0001d5900, 0xc00046ade0, 0xc00046aea0)
	/home/distorhead/go/src/github.com/flant/kubedog/pkg/tracker/job.go:48 +0x7e
created by github.com/flant/kubedog/pkg/tracker.TrackJob
	/home/distorhead/go/src/github.com/flant/kubedog/pkg/tracker/job.go:43 +0x1b8

goroutine 118 [chan send, 1 minutes]:
github.com/flant/kubedog/pkg/tracker.(*JobTracker).runPodsTrackers.func4(0xc0001d4500, 0xc00058f220, 0xc000878300)
	/home/distorhead/go/src/github.com/flant/kubedog/pkg/tracker/job.go:430 +0x1f2
created by github.com/flant/kubedog/pkg/tracker.(*JobTracker).runPodsTrackers
	/home/distorhead/go/src/github.com/flant/kubedog/pkg/tracker/job.go:401 +0x3f9

goroutine 1479 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc00104ae00, 0x0)
	/usr/local/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc00104adf0)
	/usr/local/go/src/sync/cond.go:56 +0x92
k8s.io/apimachinery/vendor/golang.org/x/net/http2.(*pipe).Read(0xc00104ade8, 0xc000c3b600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/home/distorhead/go/src/k8s.io/apimachinery/vendor/golang.org/x/net/http2/pipe.go:64 +0x8a
k8s.io/apimachinery/vendor/golang.org/x/net/http2.transportResponseBody.Read(0xc00104adc0, 0xc000c3b600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/home/distorhead/go/src/k8s.io/apimachinery/vendor/golang.org/x/net/http2/transport.go:1952 +0x95
encoding/json.(*Decoder).refill(0xc001097760, 0x0, 0x2)
	/usr/local/go/src/encoding/json/stream.go:159 +0x102
encoding/json.(*Decoder).readValue(0xc001097760, 0x0, 0x0, 0x1786ee0)
	/usr/local/go/src/encoding/json/stream.go:134 +0x222
encoding/json.(*Decoder).Decode(0xc001097760, 0x17a7160, 0xc00107cfe0, 0x0, 0x203000)
	/usr/local/go/src/encoding/json/stream.go:63 +0x78
k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc00054ade0, 0xc001019c00, 0x400, 0x400, 0x0, 0x38, 0x38)
	/home/distorhead/go/src/k8s.io/apimachinery/pkg/util/framer/framer.go:150 +0x292
k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc001098320, 0x0, 0x1bb0180, 0xc0010b83c0, 0x456b50, 0x8, 0xc000cbbeb0, 0x0, 0x1bc9b00)
	/home/distorhead/go/src/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go:77 +0x89
k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc00107cfc0, 0x1a74dc8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/distorhead/go/src/k8s.io/client-go/rest/watch/decoder.go:49 +0x7c
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc00054ae10)
	/home/distorhead/go/src/k8s.io/apimachinery/pkg/watch/streamwatcher.go:93 +0x136
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
	/home/distorhead/go/src/k8s.io/apimachinery/pkg/watch/streamwatcher.go:60 +0x9f

goroutine 687 [select]:
k8s.io/client-go/tools/cache.(*Reflector).watchHandler(0xc0008a2000, 0x1bb0740, 0xc0004081e0, 0xc000a87cc8, 0xc000b49ce0, 0xc000b7f620, 0x0, 0x0)
	/home/distorhead/go/src/k8s.io/client-go/tools/cache/reflector.go:316 +0x1db
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0008a2000, 0xc000b7f620, 0x0, 0x0)
	/home/distorhead/go/src/k8s.io/client-go/tools/cache/reflector.go:287 +0x801
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/home/distorhead/go/src/k8s.io/client-go/tools/cache/reflector.go:125 +0x33
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000a64718)
	/home/distorhead/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
```

**Comment by distorhead** [comment]
Kubedog fixed in: https://github.com/flant/kubedog/pull/67

**Comment by distorhead** [comment]
Fixed in beta channel: https://github.com/flant/werf/releases/tag/v1.0.1-beta.3

**Comment by distorhead** [comment]
Fixed in alpha channel: https://github.com/flant/werf/releases/tag/v1.0.2-alpha.0
