### ISSUE TITLE
[stapel image] More fixes for stapel

### ISSUE THREAD

**Issue by distorhead** [flant/werf#1490]
* ~Yum+ansible should work.~ Not fixed, new issue created: https://github.com/flant/werf/issues/1798.
* ~Add gpg: ansible apt_key module does not work.~
* ~Add unzip.~
* ~Unarchive for tar-archive does not work, though tar is in the stapel.~
* ~Add more docker layers for stapel image to speed up downloading.~
* ~logboek.so should be built with stapel image.~
* ~groupadd/useradd should be in stapel (package `shadow` in alpine).~

**Comment by distorhead** [comment]
> Failed to change ownership of the temporary files Ansible needs to create despite connecting as a privileged 

Problem may arise when running task with become user:

```
  - name: "Install Gemfile dependencies with bundler"
    shell: |
      set -e
      source /etc/profile.d/rvm.sh
      export BUNDLE_CACHE_PATH=/var/cache/bundle/data
      export BUNDLE_GLOBAL_GEM_CACHE=1
      bundle install -j4 --path vendor/bundle
    args:
      executable: /bin/bash
      chdir: /app
    become: yes
    become_user: app
```

**Comment by distorhead** [comment]
+ Enable replace ansible module https://docs.ansible.com/ansible/latest/modules/replace_module.html.

**Comment by distorhead** [comment]
+ Update ansible itself.

**Comment by distorhead** [comment]
+ Utf-8 chars are not allowed in python requirements.txt:

```
django_cacheops>=4.2.0,<4.3.0
# FIXME: Привет мир
django-dirtyfields>=1.3,<1.4
```


```
  - name: Python requirements develop.txt
    shell: |
      python3.6 -m pip install -q -r develop.txt
    args:
      chdir: /app/src/requirements
```

```
│ │ │ img/install  ┌ shell 'Python requirements develop.txt' [python3.6 -m pip install -q -r develop.txt]
│ │ │ img/install  │ stderr:
│ │ │ img/install  │   ERROR: Exception:
│ │ │ img/install  │   Traceback (most recent call last):
│ │ │ img/install  │     File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 188, in main
│ │ │ img/install  │       status = self.run(options, args)
│ │ │ img/install  │     File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 319, in run
│ │ │ img/install  │       self.name, wheel_cache
│ │ │ img/install  │     File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 298, in populate_requirement_set
│ │ │ img/install  │       use_pep517=options.use_pep517):
│ │ │ img/install  │     File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_file.py", line 113, in parse_requirements
│ │ │ img/install  │       for req in req_iter:
│ │ │ img/install  │     File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_file.py", line 233, in process_line
│ │ │ img/install  │       for req in parsed_reqs:
│ │ │ img/install  │     File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_file.py", line 104, in parse_requirements
│ │ │ img/install  │       filename, comes_from=comes_from, session=session
│ │ │ img/install  │     File "/usr/local/lib/python3.6/site-packages/pip/_internal/download.py", line 666, in get_file_content
│ │ │ img/install  │       content = auto_decode(f.read())
│ │ │ img/install  │     File "/usr/local/lib/python3.6/site-packages/pip/_internal/utils/encoding.py", line 38, in auto_decode
│ │ │ img/install  │       locale.getpreferredencoding(False) or sys.getdefaultencoding(),
│ │ │ img/install  │   UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 484: ordinal not in range(128)
│ │ │ img/install  │ non-zero return code
│ │ │ img/install  │ exit code: 2
│ │ │ img/install  └ shell 'Python requirements develop.txt' [python3.6 -m pip install -q -r develop.txt] (1.18 seconds) FAILED
```

**Comment by distorhead** [comment]
TODO:
* Fix build scripts: try to use `--cache-from` again.
* Infrastructure: try to store build cache on dedicated virtual machine in openstack.
* Update LFS packages list to the latest version.
* Small fixes (FIXME and TODO) in stapel/Dockerfile which need full rebuild.
* Write integration tests.
* Try to optimize flant/werf-stapel:0.2.2 from 400Mb to 200-300Mb.
