### ISSUE TITLE
Yum+ansible not working

### ISSUE THREAD

**Issue by distorhead** [flant/werf#1798]
Previous issue: https://github.com/flant/werf/issues/1490.

```
root@1df82bf6b3a1:/werf# /.werf/stapel/embedded/bin/python
Python 2.7.9 (default, Sep 30 2019, 11:23:12) 
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpm
error: Failed to initialize NSS library
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.werf/stapel/embedded/lib/python2.7/rpm/__init__.py", line 39, in <module>
    from rpm.transaction import *
  File "/.werf/stapel/embedded/lib/python2.7/rpm/transaction.py", line 5, in <module>
    from rpm._rpm import ts as TransactionSetCore
ImportError: cannot import name ts
```

All needed libraries though are imported into stapel:

```
#RUN apt install -y yum-utils
#RUN \
#cp -r /usr/lib/python2.7/dist-packages/yumutils $TOOLS/embedded/lib/python2.7/ && \
#cp -r /usr/lib/python2.7/dist-packages/yum $TOOLS/embedded/lib/python2.7/ && \
#cp -r /usr/lib/python2.7/dist-packages/rpm $TOOLS/embedded/lib/python2.7/ && \
#ln -fs $TOOLS/embedded/lib/python2.7/rpm/_rpm.x86_64-linux-gnu.so $TOOLS/embedded/lib/python2.7/rpm/_rpm.so && \
#ln -fs $TOOLS/embedded/lib/python2.7/rpm/_rpmb.x86_64-linux-gnu.so $TOOLS/embedded/lib/python2.7/rpm/_rpmb.so && \
#ln -fs $TOOLS/embedded/lib/python2.7/rpm/_rpms.x86_64-linux-gnu.so $TOOLS/embedded/lib/python2.7/rpm/_rpms.so && \
#cp /usr/lib/x86_64-linux-gnu/librpmbuild.so.8.0.1 $TOOLS/embedded/lib/ && \
#cp /usr/lib/x86_64-linux-gnu/librpmsign.so.8.0.1 $TOOLS/embedded/lib/ && \
#cp /usr/lib/x86_64-linux-gnu/librpm.so.8.0.1 $TOOLS/embedded/lib/ && \
#cp /usr/lib/x86_64-linux-gnu/librpm.so.8 $TOOLS/embedded/lib/ && \
#cp /usr/lib/x86_64-linux-gnu/librpmio.so.8 $TOOLS/embedded/lib/ && \
#cp /usr/lib/x86_64-linux-gnu/librpmsign.so.8 $TOOLS/embedded/lib/ && \
#cp /usr/lib/x86_64-linux-gnu/librpmio.so.8.0.1 $TOOLS/embedded/lib/ && \
#cp /usr/lib/x86_64-linux-gnu/librpmbuild.so.8 $TOOLS/embedded/lib/ && \
#cp /lib/x86_64-linux-gnu/libcap.so.2.25 $TOOLS/lib && \
#cp /lib/x86_64-linux-gnu/libcap.so.2 $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/liblua5.2.so.0 $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/libdb-5.3.so $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/libelf.so.1 $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/libplc4.so $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/libplds4.so $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/libnspr4.so $TOOLS/lib && \
#cp /lib/x86_64-linux-gnu/libnss_nis.so.2 $TOOLS/lib && \
#cp /lib/x86_64-linux-gnu/libnss_compat.so.2 $TOOLS/lib && \
#cp /lib/x86_64-linux-gnu/libnss_nis-2.27.so $TOOLS/lib && \
#cp /lib/x86_64-linux-gnu/libnss_files-2.27.so $TOOLS/lib && \
#cp /lib/x86_64-linux-gnu/libnss_nisplus-2.27.so $TOOLS/lib && \
#cp /lib/x86_64-linux-gnu/libnss_nisplus.so.2 $TOOLS/lib && \
#cp /lib/x86_64-linux-gnu/libnss_hesiod-2.27.so $TOOLS/lib && \
#cp /lib/x86_64-linux-gnu/libnss_dns.so.2 $TOOLS/lib && \
#cp /lib/x86_64-linux-gnu/libnss_hesiod.so.2 $TOOLS/lib && \
#cp /lib/x86_64-linux-gnu/libnss_dns-2.27.so $TOOLS/lib && \
#cp /lib/x86_64-linux-gnu/libnss_files.so.2 $TOOLS/lib && \
#cp /lib/x86_64-linux-gnu/libnss_compat-2.27.so $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/libnss_files.so $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/libnss_dns.so $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/libnss_nis.so $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/libnss_nisplus.so $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/libnss3.so $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/libnss_hesiod.so $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/libnss_compat.so $TOOLS/lib && \
#cp /usr/lib/x86_64-linux-gnu/libnssutil3.so $TOOLS/lib && \
#cp -r /usr/lib/x86_64-linux-gnu/nss $TOOLS/lib
```

Need new ideas and some rethink why it may fail.

**Comment by distorhead** [comment]
Fixed the issue for centos 6 and 7 in #1976

Created a separate issue for the centos 8: #1983
