### ISSUE TITLE
Werf deploy panic in beta

### ISSUE THREAD

**Issue by distorhead** [flant/werf#1900]
```
Running deploy
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1c3570a]
goroutine 1 [running]:
github.com/flant/werf/pkg/deploy/helm.printStatus(0x292faa0, 0xc0003803a0, 0x0)
	/werf/pkg/deploy/helm/tiller.go:490 +0x3a
github.com/flant/werf/pkg/deploy/helm.fprintReleaseStatus(0x292faa0, 0xc0003803a0, 0x7ffd1f1e1d2c, 0x19, 0x0, 0x101)
	/werf/pkg/deploy/helm/tiller.go:484 +0x268
github.com/flant/werf/pkg/deploy/helm.ReleaseUpdate(0xc000b41ae0, 0x45, 0x7ffd1f1e1d2c, 0x19, 0xc000b668f0, 0x1, 0x1, 0xc0007cfac0, 0x2, 0x2, ...)
	/werf/pkg/deploy/helm/tiller.go:324 +0x3c2
github.com/flant/werf/pkg/deploy/helm.doDeployHelmChart.func3(0x0, 0x0)
	/werf/pkg/deploy/helm/release.go:377 +0x167
github.com/flant/werf/pkg/deploy/helm.runDeployProcess(0x7ffd1f1e1d2c, 0x19, 0x7ffd1f1e1d84, 0x8, 0x0, 0x0, 0xc0007cfac0, 0x2, 0x2, 0x0, ...)
	/werf/pkg/deploy/helm/release.go:479 +0x197
github.com/flant/werf/pkg/deploy/helm.doDeployHelmChart.func5(0x1, 0xc0007d67a0)
	/werf/pkg/deploy/helm/release.go:449 +0x24c
github.com/flant/logboek.logProcess.func1(0x1fcd720, 0xc0007d67a0)
	/go/pkg/mod/github.com/flant/logboek@v0.2.6-0.20190918091020-d00ba619a349/process.go:199 +0x26
github.com/flant/logboek.logProcess(0x224ef83, 0xe, 0x0, 0x0, 0x0, 0x27464c0, 0xc00041cdc0, 0x1, 0xc00041cdc0)
	/go/pkg/mod/github.com/flant/logboek@v0.2.6-0.20190918091020-d00ba619a349/process.go:206 +0x9d
github.com/flant/logboek.LogProcess(0x224ef83, 0xe, 0x0, 0x0, 0x0, 0x27464c0, 0xc00041cdc0, 0x0, 0x0)
	/go/pkg/mod/github.com/flant/logboek@v0.2.6-0.20190918091020-d00ba619a349/process.go:188 +0x56
github.com/flant/werf/pkg/deploy/helm.doDeployHelmChart(0xc000b41ae0, 0x45, 0x7ffd1f1e1d2c, 0x19, 0x7ffd1f1e1d84, 0x8, 0x0, 0x0, 0xc0007cfac0, 0x2, ...)
	/werf/pkg/deploy/helm/release.go:439 +0x3ab
github.com/flant/werf/pkg/deploy/helm.DeployHelmChart.func1(0xc000460d20, 0x2935080)
	/werf/pkg/deploy/helm/release.go:160 +0x8e
github.com/flant/werf/pkg/lock.(*Base).WithLock(0xc000460d20, 0x2935080, 0xc000460d50, 0xc000ad2120, 0x1fd1120, 0x290e559)
	/werf/pkg/lock/base.go:70 +0x60
github.com/flant/werf/pkg/lock.(*File).WithLock(0xc000460d20, 0x4e94914f0000, 0xc00074bf00, 0xc0007cfae0, 0xc000ad2120, 0xc000dcc700, 0x34)
	/werf/pkg/lock/file_unix.go:59 +0xa5
github.com/flant/werf/pkg/lock.WithLock(0xc00074bf40, 0x34, 0x0, 0x0, 0xc000ad2120, 0xc00074bf40, 0x34)
	/werf/pkg/lock/lock.go:79 +0x107
github.com/flant/werf/pkg/deploy/helm.withLockedHelmRelease(0x7ffd1f1e1d2c, 0x19, 0xc000ad2120, 0x0, 0x20)
	/werf/pkg/deploy/helm/release.go:155 +0x10b
github.com/flant/werf/pkg/deploy/helm.DeployHelmChart(0xc000b41ae0, 0x45, 0x7ffd1f1e1d2c, 0x19, 0x7ffd1f1e1d84, 0x8, 0x0, 0x0, 0xc0007cfac0, 0x2, ...)
	/werf/pkg/deploy/helm/release.go:159 +0xd1
github.com/flant/werf/pkg/deploy/werf_chart.(*WerfChart).Deploy(0xc0005fbc80, 0x7ffd1f1e1d2c, 0x19, 0x7ffd1f1e1d84, 0x8, 0x0, 0x0, 0xc0007cfac0, 0x2, 0x2, ...)
	/werf/pkg/deploy/werf_chart/werf_chart.go:160 +0x351
github.com/flant/werf/pkg/deploy.Deploy.func2(0xc00046a270, 0xc000d2b6c0)
	/werf/pkg/deploy/deploy.go:92 +0x139
github.com/flant/werf/pkg/deploy/helm.WithExtra(0xc0004601b0, 0xc0004601e0, 0xc000d2b770, 0x45, 0xc00027cdc0)
	/werf/pkg/deploy/helm/templates.go:255 +0x69
github.com/flant/werf/pkg/deploy.Deploy(0xc00005c0a4, 0x41, 0x2957480, 0xc0007369f0, 0x7ffd1f1e1d2c, 0x19, 0x7ffd1f1e1d84, 0x8, 0xc000050074, 0xd, ...)
	/werf/pkg/deploy/deploy.go:91 +0x354
github.com/flant/werf/cmd/werf/deploy.runDeploy(0x0, 0x0)
	/werf/cmd/werf/deploy/main.go:247 +0xe45
github.com/flant/werf/cmd/werf/deploy.NewCmd.func1.1(0xbf6970a055a0b874, 0x78ddb8e)
	/werf/cmd/werf/deploy/main.go:64 +0x22
github.com/flant/werf/cmd/werf/common.LogRunningTime(0x27465a8, 0x0, 0x0)
	/werf/cmd/werf/common/common.go:749 +0x61
github.com/flant/werf/cmd/werf/deploy.NewCmd.func1(0xc000337b80, 0xc000b36c80, 0x0, 0xa, 0x0, 0x0)
	/werf/cmd/werf/deploy/main.go:63 +0x8b
github.com/spf13/cobra.(*Command).execute(0xc000337b80, 0xc000b36b40, 0xa, 0xa, 0xc000337b80, 0xc000b36b40)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0xc000336a00, 0x20, 0x2, 0xc00065b900)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2f8
github.com/spf13/cobra.(*Command).Execute(0xc000336a00, 0xc000b61f70, 0x3)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864 +0x2b
main.main()
	/werf/cmd/werf/main.go:128 +0x5bb
```

```
werf 1.0/beta: update is disabled, use local latest v1.0.4-beta.16
```

**Comment by distorhead** [comment]
Some old issue here.
