### ISSUE TITLE
werf helm dependency list return invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by codmw44** [flant/werf#2388]
I execute `werf helm dependency list` command with requirements.yaml
```
#requirements.yaml
dependencies:
  - name: nginx-ingress
    version: "1.36.3"
    repository: "@stable"
```

output command:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25ce868]

goroutine 1 [running]:
k8s.io/helm/pkg/chartutil.LoadFiles.func1(0x2dba120, 0xc000100a50)
	/home/ubuntu/go/pkg/mod/github.com/flant/helm@v0.0.0-20200302114220-d40ba0adc0f1/pkg/chartutil/load.go:269 +0x328
k8s.io/helm/pkg/chartutil.WithSkipChartYamlFileValidation(...)
	/home/ubuntu/go/pkg/mod/github.com/flant/helm@v0.0.0-20200302114220-d40ba0adc0f1/pkg/chartutil/load.go:48
k8s.io/helm/pkg/chartutil.LoadFiles(0xc0006787c0, 0x5, 0x8, 0x0, 0x0, 0xc00091d5c0)
	/home/ubuntu/go/pkg/mod/github.com/flant/helm@v0.0.0-20200302114220-d40ba0adc0f1/pkg/chartutil/load.go:239 +0xc7f
k8s.io/helm/pkg/chartutil.LoadDir(0xc00091d500, 0x3c, 0x336ef00, 0xc00097c0d0, 0x0)
	/home/ubuntu/go/pkg/mod/github.com/flant/helm@v0.0.0-20200302114220-d40ba0adc0f1/pkg/chartutil/load.go:411 +0x2a1
k8s.io/helm/pkg/chartutil.Load(0xc00091d500, 0x3c, 0x0, 0xc0009a3850, 0x232b7e5)
	/home/ubuntu/go/pkg/mod/github.com/flant/helm@v0.0.0-20200302114220-d40ba0adc0f1/pkg/chartutil/load.go:84 +0x8c
github.com/flant/werf/cmd/werf/helm/dependency.(*dependencyListCmd).run.func1(0x0, 0x0)
	/home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/helm/dependency/dependency_list.go:75 +0x4d
k8s.io/helm/pkg/chartutil.WithSkipChartYamlFileValidation(...)
	/home/ubuntu/go/pkg/mod/github.com/flant/helm@v0.0.0-20200302114220-d40ba0adc0f1/pkg/chartutil/load.go:48
github.com/flant/werf/cmd/werf/helm/dependency.(*dependencyListCmd).run(0xc000875ec0, 0xc0001978e0, 0x0)
	/home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/helm/dependency/dependency_list.go:74 +0xad
github.com/flant/werf/cmd/werf/helm/dependency.newDependencyListCmd.func1(0xc000914500, 0x46ef088, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/helm/dependency/dependency_list.go:59 +0x16f
github.com/spf13/cobra.(*Command).execute(0xc000914500, 0x46ef088, 0x0, 0x0, 0xc000914500, 0x46ef088)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000148c80, 0xc0009a3f30, 0x4, 0x4)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/main.go:142 +0x625
```

It reproduced at 1.0 stable and at 1.1 ea version

**Comment by alexey-igrychev** [comment]
Yup, it is a bug.
We will fix it in upcoming releases.
Thanks for the report and your perseverance).

**Comment by alexey-igrychev** [comment]
The panic has been fixed.

But this solution does not resolve your error.
I have tried to perform all steps on a fresh chart with your requirements.yaml file and I have not faced anything wrong.
```
$ werf helm dependency list
NAME            VERSION REPOSITORY      STATUS
nginx-ingress   1.36.3  @stable         missing

$ werf helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
        Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Downloading nginx-ingress from repo https://kubernetes-charts.storage.googleapis.com
Deleting outdated charts

$ werf helm dependency list
NAME            VERSION REPOSITORY      STATUS
nginx-ingress   1.36.3  @stable         ok
```

Let's wait for the recent release and check the error message.

**Comment by codmw44** [comment]
I drop `requirements.yaml` to `.helm/charts` and it was the mistake
`requirements.yaml`  should be in `.helm/` folder
